<?php

namespace Container6huFxic;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9kGZ_3UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9kGZ.3U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9kGZ.3U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tasks' => ['privates', '.errored..service_locator.9kGZ.3U.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.9kGZ.3U": it references class "App\\Entity\\Task" but no such service exists.'],
        ], [
            'tasks' => 'App\\Entity\\Task',
        ]);
    }
}
