<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ6v9YsX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ6v9YsX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ6v9YsX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ6v9YsX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ6v9YsX\App_KernelDevDebugContainer([
    'container.build_hash' => 'J6v9YsX',
    'container.build_id' => '6b1b5a90',
    'container.build_time' => 1608079691,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ6v9YsX');
