<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNMqtEte\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNMqtEte/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNMqtEte.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNMqtEte\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNMqtEte\App_KernelDevDebugContainer([
    'container.build_hash' => 'NMqtEte',
    'container.build_id' => '022d6737',
    'container.build_time' => 1607995660,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNMqtEte');
