<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKkATJ4D\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKkATJ4D/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKkATJ4D.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKkATJ4D\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKkATJ4D\App_KernelDevDebugContainer([
    'container.build_hash' => 'KkATJ4D',
    'container.build_id' => 'a812e44b',
    'container.build_time' => 1608915433,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKkATJ4D');
